version: '2'
services:
  app:
    restart: "no"
    image: '${DOCKER_BASE_IMAGE}:${DOCKER_BASE_TAG}-dev'
    container_name: '${COMPOSE_PROJECT_NAME}'
    depends_on:
      - data
      - mysql
      - import
    ports:
      - "${APP_IP}:80:80"
      - "${APP_IP}:443:443"
    env_file:
      - .env
    environment:
      - 'APP_MYSQL_HOST=${COMPOSE_PROJECT_NAME}-mysql'
      - APACHE_LOG_DIR=/var/www/logs
    volumes:
      - ${APP_SSH_DIR}:/home/ssh-labor/.ssh
      - ${APP_WORKING_DIR}:/var/www/html
      - ${APP_LOG_DIR}:/var/www/logs
      - ${APP_OPT_DIR}/build_and_bootstrap-env.sh:/opt/build_and_bootstrap-env.sh
      - ${APP_OPT_DIR}/build_and_bootstrap-dir.sh:/opt/build_and_bootstrap-dir.sh
      - ${APP_OPT_DIR}/bootstrap-dev.sh:/opt/bootstrap-dev.sh
      - ${APP_OPT_DIR}/bootstrap-project.sh:/opt/bootstrap-project.sh
    volumes_from:
      - data
  mysql:
    restart: "no"
    container_name: '${COMPOSE_PROJECT_NAME}-mysql'
    image: 'mysql:5'
    env_file:
      - .env
    ports:
      - "${APP_IP}:3306:3306"
  data:
    restart: "no"
    container_name: '${COMPOSE_PROJECT_NAME}-data'
    image: ubuntu
    volumes:
      - '${APP_DATA_DIR}:/var/www/html_data'
  import:
    restart: "no"
    container_name: '${COMPOSE_PROJECT_NAME}-import'
    image: 'labordigital/import-export:latest'
    depends_on:
      - mysql
      - data
    env_file:
      - .env
    environment:
      - 'APP_MYSQL_HOST=${COMPOSE_PROJECT_NAME}-mysql'
      - MYSQL_PORT=3306
    volumes:
      - '${APP_IMPORT_DIR}:/var/www/html_import'
    volumes_from:
      - data