name: Build and push base - on push

on:
  schedule:
    - cron: '0 8 * * *' # Rebuild the images every night @todo twice per week will be enough -> just for testing

jobs:
  build-php53:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Base Image
      - name: Build the Docker Base image
        run: cd php53/php53 && docker build . --file Dockerfile --tag labordigital/docker-base-images:php53
      - name: Push the image
        run: docker push labordigital/docker-base-images:php53

      # Dev Image
      - name: Build the Docker Dev image
        run: cd php53/php53-dev && docker build . --file Dockerfile --tag labordigital/docker-base-images:php53-dev
      - name: Push the image
        run: docker push labordigital/docker-base-images:php53-dev

  build-php56:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Base Image
      - name: Build the Docker Base image
        run: cd php56/php56 && docker build . --file Dockerfile --tag labordigital/docker-base-images:php56
      - name: Push the image
        run: docker push labordigital/docker-base-images:php56

      # Dev Image
      - name: Build the Docker Dev image
        run: cd php56/php56-dev && docker build . --file Dockerfile --tag labordigital/docker-base-images:php56-dev
      - name: Push the image
        run: docker push labordigital/docker-base-images:php56-dev

  build-php70:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Base Image
      - name: Build the Docker Base image
        run: cd php70/php70 && docker build . --file Dockerfile --tag labordigital/docker-base-images:php70
      - name: Push the image
        run: docker push labordigital/docker-base-images:php70

      # Dev Image
      - name: Build the Docker Dev image
        run: cd php70/php70-dev && docker build . --file Dockerfile --tag labordigital/docker-base-images:php70-dev
      - name: Push the image
        run: docker push labordigital/docker-base-images:php70-dev