name: Build and push docker images

on:
  schedule:
    #0 2 * * 6
    - cron '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get the tag
        id: vars
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/heads/})"
